// Seed data — imported by db.ts for auto-seeding on first boot
export const SEED_CATS = [
  { image: 'IMG_0443.jpg',   name: 'Mr. Fluffins',        neighborhood: 'Exarcheia',    quote: 'The revolution will be napped through.' },
  { image: 'IMG_0444.jpg',   name: 'Souvlaki',            neighborhood: 'Monastiraki',  quote: 'I have seen tourists. I have eaten their gyros. I regret nothing.' },
  { image: 'IMG_0445.jpg',   name: 'Baba',                neighborhood: 'Psiri',        quote: 'Every doorstep is a throne if you sit on it long enough.' },
  { image: 'IMG_0911.jpg',   name: 'Tzatziki',            neighborhood: 'Plaka',        quote: 'Cool. Smooth. Impossible to ignore. That\'s me.' },
  { image: 'IMG_0912.jpg',   name: 'Dorito',              neighborhood: 'Pangrati',     quote: 'Triangular? No. Lethal? Absolutely.' },
  { image: 'IMG_0913.jpg',   name: 'Stavros',             neighborhood: 'Kolonaki',     quote: 'I don\'t eat dry food. I have standards.' },
  { image: 'IMG_0914.jpg',   name: 'Aristoteles',         neighborhood: 'Thisio',       quote: 'The Acropolis is fine. But have you seen my belly in the sunlight?' },
  { image: 'IMG_1053.jpeg',  name: 'Loukoumas',           neighborhood: 'Gazi',         quote: 'Round, sweet, irresistible. We have things in common.' },
  { image: 'IMG_1057.jpeg',  name: 'Retsina',             neighborhood: 'Keramikos',    quote: 'An acquired taste. Not everyone deserves me.' },
  { image: 'IMG_1058.jpeg',  name: 'Feta',                neighborhood: 'Kypseli',      quote: 'Protected designation of origin. You cannot replicate this.' },
  { image: 'IMG_1061.jpg',   name: 'Zorba',               neighborhood: 'Petralona',    quote: 'I dance. I leap. I knock the vase off the table. I live.' },
  { image: 'IMG_1062.jpg',   name: 'Metaxa',              neighborhood: 'Koukaki',      quote: 'Five stars? Seven? I count in naps.' },
  { image: 'IMG_1102.jpg',   name: 'Gyros',               neighborhood: 'Neos Kosmos',  quote: 'Turning, always turning. Life is a spit.' },
  { image: 'IMG_1750.jpg',   name: 'Spanakos',            neighborhood: 'Zografou',     quote: 'I am full of greens. And attitude.' },
  { image: 'IMG_1751.jpg',   name: 'Captain Acropolis',   neighborhood: 'Vyronas',      quote: 'I guard these streets. No one asked me to. I do it anyway.' },
  { image: 'IMG_1828.jpg',   name: 'Baklava',             neighborhood: 'Kallithea',    quote: 'Many layers. Dangerously sweet. Impossible to put down.' },
  { image: 'IMG_1829.jpg',   name: 'Ouzo',                neighborhood: 'Piraeus',      quote: 'Goes down smooth. Then the world gets blurry. You\'re welcome.' },
  { image: 'IMG_2695.jpg',   name: 'Pita',                neighborhood: 'Kesariani',    quote: 'Flat? Yes. Underrated? Absolutely.' },
  { image: 'IMG_2696.jpg',   name: 'Tiramisu',            neighborhood: 'Glyfada',      quote: 'Not technically Greek. But I live here now. Deal with it.' },
  { image: 'IMG_2697.jpg',   name: 'Nikitas the Wise',    neighborhood: 'Kifisia',      quote: 'I have thought about this. The answer is: more treats.' },
  { image: 'IMG_2823.jpg',   name: 'Sir Purrfect',        neighborhood: 'Chalandri',    quote: 'Knighthood is a state of mind. I achieved it without trying.' },
  { image: 'IMG_2831.jpg',   name: 'Don Kebab',           neighborhood: 'Metaxourgio',  quote: 'I run this block. Every corner. Every alley. Every overturned bin.' },
  { image: 'IMG_3291.jpg',   name: 'Maestro Fluffini',    neighborhood: 'Marousi',      quote: 'I conduct the pigeons from my balcony every morning. They are not ready.' },
  { image: 'IMG_3737.jpg',   name: 'Lord Moustakas',      neighborhood: 'Moschato',     quote: 'The moustache is real. The authority is earned.' },
  { image: 'IMG_3738.jpg',   name: 'Princess Olive',      neighborhood: 'Tavros',       quote: 'I am small. I am briny. I contain multitudes.' },
  { image: 'IMG_3739.jpeg',  name: 'El Gato',             neighborhood: 'Ilioupoli',    quote: 'They said I\'d never make it in Athens. Seventeen naps later, here I am.' },
  { image: 'IMG_3740.jpeg',  name: 'Comrade Whiskers',    neighborhood: 'Exarcheia',    quote: 'Property is theft. Especially when the property is your lunch.' },
  { image: 'IMG_3741.jpeg',  name: 'Baron von Fluff',     neighborhood: 'Dafni',        quote: 'The barony extends to all sunny patches within a 200m radius.' },
  { image: 'IMG_3742.jpeg',  name: 'Duchess of Plaka',    neighborhood: 'Plaka',        quote: 'The tourists photograph me. I allow it. It is a mercy.' },
  { image: 'IMG_3743.jpg',   name: 'Mr. Olives',          neighborhood: 'Nea Smyrni',   quote: 'Bitter at first. Then you can\'t stop.' },
  { image: 'IMG_3854.jpg',   name: 'Moussaka',            neighborhood: 'Pangrati',     quote: 'Layered. Baked. Impossible to rush. That\'s wisdom.' },
  { image: 'IMG_3855.jpg',   name: 'Pastitsio',           neighborhood: 'Kypseli',      quote: 'They call me comfort food. I prefer: essential being.' },
  { image: 'IMG_3856.jpg',   name: 'Stifado',             neighborhood: 'Peristeri',    quote: 'Slow-cooked. Patient. Devastating.' },
  { image: 'IMG_3947.jpg',   name: 'Kolokythaki',         neighborhood: 'Thisio',       quote: 'Do not underestimate the zucchini. Do not underestimate me.' },
  { image: 'IMG_3948.jpg',   name: 'Fasolada',            neighborhood: 'Kesariani',    quote: 'The national dish. I take that very seriously.' },
  { image: 'IMG_3949.jpg',   name: 'Revithia',            neighborhood: 'Vyronas',      quote: 'Ancient. Humble. Nourishing. Sunday energy only.' },
  { image: 'IMG_4267.jpg',   name: 'Imam',                neighborhood: 'Koukaki',      quote: 'The story says the imam fainted when he tasted me. I believe it.' },
  { image: 'IMG_4268.jpg',   name: 'Kleftiko',            neighborhood: 'Metaxourgio',  quote: 'Stolen. Slow-cooked. Legendary. A life well lived.' },
  { image: 'IMG_4565.JPG',   name: 'Gemista',             neighborhood: 'Gazi',         quote: 'I am full of life. Literally. Stuff me with anything and I shine.' },
  { image: 'IMG_4566.JPG',   name: 'Briami',              neighborhood: 'Neos Kosmos',  quote: 'We are all vegetables in the end. Make it count.' },
  { image: 'IMG_4567.JPG',   name: 'Magiritsa',           neighborhood: 'Psiri',        quote: 'Once a year. Midnight. You will think of me.' },
  { image: 'IMG_4568.JPG',   name: 'Kokoretsi',           neighborhood: 'Keramikos',    quote: 'Not for the faint of heart. Neither am I.' },
  { image: 'IMG_4569.JPG',   name: 'Kontosouvli',         neighborhood: 'Kallithea',    quote: 'The spit turns. I wait. Patience is power.' },
  { image: 'IMG_4832.jpg',   name: 'Bougatsa',            neighborhood: 'Monastiraki',  quote: 'Crispy outside. Custard inside. I contain surprises.' },
  { image: 'IMG_4833.jpg',   name: 'Galakto',             neighborhood: 'Kolonaki',     quote: 'Milk-based. Aristocratic. Sprinkled with cinnamon for drama.' },
  { image: 'IMG_4834.jpg',   name: 'Halva',               neighborhood: 'Plaka',        quote: 'Sesame and honey. Simple. Ancient. Perfect.' },
  { image: 'IMG_5480.jpg',   name: 'Rahat',               neighborhood: 'Glyfada',      quote: 'Turkish delight is my cousin. We don\'t talk.' },
  { image: 'IMG_5483.jpeg',  name: 'Loukoum',             neighborhood: 'Piraeus',      quote: 'Powdered sugar on the outside. Mystery within.' },
  { image: 'IMG_5485.jpeg',  name: 'Melomakarona',        neighborhood: 'Zografou',     quote: 'Christmas-coded. December energy all year long.' },
  { image: 'IMG_5486.jpeg',  name: 'Diples',              neighborhood: 'Pangrati',     quote: 'Folded like origami. Dripping with honey. Life should be so lucky.' },
  { image: 'IMG_5882.jpeg',  name: 'Saragli',             neighborhood: 'Marousi',      quote: 'Like baklava but rolled. I take a different path. It\'s still nuts.' },
  { image: 'IMG_5884.jpg',   name: 'Kadaifi',             neighborhood: 'Nea Smyrni',   quote: 'Shredded. Drenched. Proud.' },
  { image: 'IMG_6144.jpg',   name: 'Taramosalata',        neighborhood: 'Moschato',     quote: 'Pink. Potent. Divisive at parties. My kind of energy.' },
  { image: 'IMG_6145.jpg',   name: 'Skordalia',           neighborhood: 'Ilioupoli',    quote: 'I am garlic. Unashamed. You will remember me.' },
  { image: 'IMG_6505.jpg',   name: 'Horiatiki',           neighborhood: 'Dafni',        quote: 'No lettuce. Never. We have standards in this salad.' },
  { image: 'IMG_6506.jpg',   name: 'Tzatziki II',         neighborhood: 'Exarcheia',    quote: 'Yes, there are two of us. The neighborhood needed it.' },
  { image: 'IMG_6513.JPG',   name: 'Sikomaida',           neighborhood: 'Kesariani',    quote: 'A fig pressed flat, dried in the sun. Patience personified.' },
  { image: 'IMG_6514.JPG',   name: 'Xerotigano',          neighborhood: 'Peristeri',    quote: 'Twisted and fried at weddings. I attend all celebrations uninvited.' },
  { image: 'IMG_6515.JPG',   name: 'Spanakopita',         neighborhood: 'Thisio',       quote: 'Spinach and cheese in phyllo. A masterpiece hiding its complexity.' },
  { image: 'IMG_6516.JPG',   name: 'Tiropita',            neighborhood: 'Petralona',    quote: 'Just cheese. Pure cheese. No apologies.' },
  { image: 'IMG_6841.jpg',   name: 'Professor Paws',      neighborhood: 'Zografou',     quote: 'I have lectured at the University. Mostly to pigeons. They fail every year.' },
  { image: 'IMG_6842.jpg',   name: 'Dr. Hairball',        neighborhood: 'Kolonaki',     quote: 'My thesis: every warm surface is a valid sleeping location.' },
  { image: 'IMG_6869.jpg',   name: 'Count Fluffula',      neighborhood: 'Vyronas',      quote: 'I only come out at dusk. I find the daylight... excessive.' },
  { image: 'IMG_6871.jpg',   name: 'Madame Whiskero',     neighborhood: 'Kifisia',      quote: 'Elegance is not learned. It is inherited. I have it all.' },
  { image: 'IMG_6872.jpg',   name: 'The Chairman',        neighborhood: 'Metaxourgio',  quote: 'I chair all meetings in this alley. Minutes are not kept.' },
  { image: 'IMG_6873.jpg',   name: 'Lieutenant Tabby',    neighborhood: 'Piraeus',      quote: 'I have served on three fishing boats. Retired with honour.' },
  { image: 'IMG_7424.JPG',   name: 'Archimedes',          neighborhood: 'Gazi',         quote: 'Give me a warm spot and I will sleep the world.' },
  { image: 'IMG_7425.jpg',   name: 'Socrates Jr.',        neighborhood: 'Keramikos',    quote: 'I know that I know nothing. Except where the food bowl is.' },
  { image: 'IMG_7426.jpg',   name: 'Plato\'s Shadow',     neighborhood: 'Psiri',        quote: 'The ideal cat exists in the realm of forms. I am its earthly copy.' },
  { image: 'IMG_7427.jpg',   name: 'Heraclitus',          neighborhood: 'Monastiraki',  quote: 'You cannot pet the same cat twice. I am always moving.' },
  { image: 'IMG_7471.JPG',   name: 'Diogenes',            neighborhood: 'Exarcheia',    quote: 'I live in a box by choice. Alexander the Great once blocked my sun. I told him to move.' },
  { image: 'IMG_7472.JPG',   name: 'Pythagoras',          neighborhood: 'Pangrati',     quote: 'The sum of all naps equals comfort squared.' },
  { image: 'IMG_7474.JPG',   name: 'Epicurus',            neighborhood: 'Koukaki',      quote: 'Pleasure is the highest good. The fish from the market agrees.' },
  { image: 'IMG_7602.JPG',   name: 'Demosthenes',         neighborhood: 'Kallithea',    quote: 'I once gave a speech to a wall for three hours. The wall was persuaded.' },
  { image: 'IMG_7603.jpg',   name: 'Thucydides',          neighborhood: 'Neos Kosmos',  quote: 'History is made by those who show up. I show up. For the food.' },
  { image: 'IMG_7604.jpg',   name: 'Pericles',            neighborhood: 'Thisio',       quote: 'In this neighborhood, I am the golden age.' },
  { image: 'IMG_7605.jpg',   name: 'Themistocles',        neighborhood: 'Piraeus',      quote: 'A maritime power. I have surveyed this port. It smells of sardines. Good.' },
  { image: 'IMG_7680.jpg',   name: 'Odysseus',            neighborhood: 'Nea Smyrni',   quote: 'Twenty years to get home. Every alley felt like the Cyclops\' cave.' },
  { image: 'IMG_7682.jpg',   name: 'Achilles\' Heel',     neighborhood: 'Zografou',     quote: 'Invincible everywhere except the ankles. I avoid stairs.' },
  { image: 'IMG_7683.jpg',   name: 'Ajax',                neighborhood: 'Ilioupoli',    quote: 'Fiercest warrior in the alley. Lost the armor to the other cat. Still bitter.' },
  { image: 'IMG_7684.jpg',   name: 'Penelope',            neighborhood: 'Kypseli',      quote: 'I waited. I unraveled. I waited again. I am patient beyond reason.' },
  { image: 'IMG_7685.jpg',   name: 'Circe',               neighborhood: 'Petralona',    quote: 'I turned three dogs into confused dogs. They were already dogs. Still counts.' },
  { image: 'IMG_7688.jpg',   name: 'Calypso',             neighborhood: 'Glyfada',      quote: 'Seven years I kept him. He left. The tuna stayed. I prefer the tuna.' },
  { image: 'IMG_7690.jpg',   name: 'Cassandra',           neighborhood: 'Marousi',      quote: 'I prophesied the bin would be knocked over. No one listened. It was knocked over.' },
  { image: 'IMG_7691.jpg',   name: 'Medusa',              neighborhood: 'Dafni',        quote: 'One look and you are frozen. That is not a power. That is just charisma.' },
  { image: 'IMG_7692.jpg',   name: 'Prometheus',          neighborhood: 'Keramikos',    quote: 'I brought fire to this alley. Specifically, I knocked over a candle. Worth it.' },
  { image: 'IMG_7693.jpg',   name: 'Icarus',              neighborhood: 'Moschato',     quote: 'I jumped from the second floor. I am fine. I did it again.' },
  { image: 'IMG_7696.jpg',   name: 'Hermes',              neighborhood: 'Psiri',        quote: 'Messenger of the gods. Currently delivering dead mice to the wrong doors.' },
  { image: 'IMG_7698.jpg',   name: 'Poseidon',            neighborhood: 'Piraeus',      quote: 'God of the sea. I dislike water. We have reached an agreement.' },
  { image: 'IMG_8282.jpg',   name: 'Apollo',              neighborhood: 'Kolonaki',     quote: 'God of light and music. Also this sunny spot on the marble step.' },
  { image: 'IMG_8324.jpg',   name: 'Artemis',             neighborhood: 'Kesariani',    quote: 'Goddess of the hunt. Current prey: one very fast pigeon. Tomorrow.' },
  { image: 'IMG_8325.jpg',   name: 'Athena',              neighborhood: 'Plaka',        quote: 'Goddess of wisdom. This whole city is named after me. You\'re welcome.' },
  { image: 'IMG_8489.jpg',   name: 'Hephaestus',          neighborhood: 'Gazi',         quote: 'God of the forge. I knocked the toaster off the counter. Still working on it.' },
  { image: 'IMG_8500.jpg',   name: 'Ares',                neighborhood: 'Exarcheia',    quote: 'God of war. The battle for the sunny corner at noon. I always win.' },
  { image: 'IMG_8700.jpg',   name: 'Dionysus',            neighborhood: 'Metaxourgio',  quote: 'God of wine and revelry. I found some leftover souvlaki at 3am. Transcendent.' },
  { image: 'IMG_8791.JPG',   name: 'Demeter',             neighborhood: 'Nea Smyrni',   quote: 'Goddess of the harvest. I watch the fruit market with intensity.' },
  { image: 'IMG_8902.JPG',   name: 'Hera',                neighborhood: 'Kifisia',      quote: 'Queen of Olympus. I survey my domain from the highest point of the couch.' },
  { image: 'IMG_8903.JPG',   name: 'Zeus',                neighborhood: 'Pangrati',     quote: 'Father of gods and cats. The thunder last Tuesday? That was me. Stretching.' },
  { image: 'ec68e4ff-1c4f-4362-a7f3-18bc707b4afb.JPG', name: 'The Stranger', neighborhood: 'Unknown', quote: 'I arrived without a name, without a past. Only a sunbeam and a purpose.' },
];
